import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Render the application's root HTML structure with a dark, full-height layout.
 *
 * Renders the top-level `<html>` and `<body>` elements and places `children` inside the body.
 *
 * @param children - React nodes to be rendered within the document body
 * @returns The root HTML element containing the provided `children`
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-full antialiased">
      <body className="min-h-full flex flex-col" suppressHydrationWarning>{children}</body>
    </html>
  );
}
